### ISSUE TITLE
Upgrading to channels v3

### ISSUE THREAD

**Issue by tommcn** [csdenboer/channels-demultiplexer#1]
Hello, 

I was wondering if you were considering updating this project to be compatible with the new channels v3 interface. If you want, I can open a PR with the changes, which are very minor.

Thank You

**Comment by csdenboer** [comment]
Hi,

Yes, I would like to update this project to Channels 3, but I haven’t found the time to do so. A PR would very much be appreciated!

**Comment by csdenboer** [comment]
Thank you very much for your contribution! I've just released v2.0.0 which includes support for Channels 3.
